[package]
name = "api"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
hyper = {version = "0.9.11", features = ["serde"]}
serde_json = "0.8.3"
serde = "0.8.16"
serde_derive = "0.8.16"
