[package]
name = "web"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
clap = "2.17.0"
hyper = {version = "0.9.11", features = ["serde"]}
redis = "0.7.0"
iron = "0.4.0"
mount = "0.2.1"
router = "0.4.0"
params = "0.5.0"
rand = "0.3.14"
plugin = "0.2.6"
